# Server health configuration file
# It contains the operating system, the reboot time, the RAM clearing frequency, and the list of services.

# The operating system used by the server. Possible values: "windows" or "linux" or "mac".
os = "windows"

# The time at which the server should automatically restart each day. Format: "HH:MM" (24-hour format)
restart_hour = "13:50"

# The interval (in hours) at which the RAM cache should be cleared. It must be an Integer
cache_clear_interval = 6

# List of service executables that should be restarted after a reboot. Provide full paths to the executables.
services = [
    "C:\\Program Files\\Audacity\\Audacity.exe",
    "C:\\Users\\marti\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Wallpaper Engine.url"
]
